server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/spring_ai
    username: postgres
    password: postgres   # ← 改成 postgres docker容器的账号密码
    driver-class-name: org.postgresql.Driver
  ai:
    dashscope:
      api-key: sk-8f196f4a6a394c248c15808a619a85ee
      chat:
        options:
          model: qwen-plus
      embedding:          # ：安装“脑子”，让 AI 理解语义
        enabled: true
        options:
          model: text-embedding-v3
    vectorstore:         # 安装“书架”，让他能存能查
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yang.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志配置，方便看 Spring AI 的调用细节
logging:
  level:
    org.springframework.ai: DEBUG
